print("digite um numero")
numero=input()
numero=int(numero)
print ("a tabuada de 1 a 10 do numero", numero,"é:")
print(1*numero,2*numero,3*numero,4*numero,5*numero,6*numero,7*numero,8*numero,9*numero,10*numero)
